project:
  type: website
  render: 
    - "*.qmd"
    - "!data/**"

website:
  title: "415"
  navbar:
    left:
      - text: "HOEs"
        menu: 
          - text: "ex1"
            href: "HOE/ex1/ex1.html"
          - text: "ex2"
            href: "HOE/ex2/ex2.html"
          - text: "ex3"
            href: "HOE/ex3/ex3.html"
          - text: "ex4"
            href: "HOE/ex4/ex4.html"
          - text: "ex5"
            href: "HOE/ex5/ex5.html"
          - text: "ex6"
            href: "HOE/ex6/ex6.html"
          - text: "ex7"
            href: "HOE/ex7/ex7.html"
          - text: "ex8"
            href: "HOE/ex8/ex8.html"
          - text: "ex9"
            href: "HOE/ex9/ex9.html"
          
      - text: "ICEs"
        menu:
          - text: "ice1"
            href: "ICE/ex1/ice1.html"
          - text: "ice2"
            href: "ICE/ex2/ice2.html"
          - text: "ice3"
            href: "ICE/ex3/ice3.html"
          - text: "ice4"
            href: "ICE/ex4/ice4.html"
          - text: "ice5"
            href: "ICE/ex5/ice5.html"
          - text: "ice6"
            href: "ICE/ex6/ice6.html"
          - text: "ice7"
            href: "ICE/ex7/ice7.html"
          - text: "ice8"
            href: "ICE/ex8/ice8.html"
          - text: "ice9"
            href: "ICE/ex9/ice9.html"
      - text: "Takehomes"
        menu:
          - text: "takehome1"
            href: "THE/THE1/takehome1.html"
          - text: "takehome2"
            href: "THE/THE2/takehome2.html"
          - text: "takehome3"
            href: "THE/THE3/takehome3.html"
    right: 
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

