project:
  type: website
  render: 
    - "*.qmd"
    - "!data/**"

website:
  title: "415"
  navbar:
    left:
      - text: "HOEs"
        menu: 
          - text: "ex1"
            href: "HOE/ex1/ex1.html"
          - text: "ex2"
            href: "HOE/ex2/ex2.html"
          - text: "ex3"
            href: "HOE/ex3/ex3.html"
          - text: "ex4"
            href: "HOE/ex4/ex4.html"
          - text: "ex5"
            href: "HOE/ex5/ex5.html"
          - text: "ex6"
            href: "HOE/ex6/ex6.html"
          - text: "ex7"
            href: "HOE/ex7/ex7.html"
      - text: "ICEs"
        menu:
          - text: "ice1"
            href: "ICE/ex1/ice1.html"
          - text: "ice2"
            href: "ICE/ex2/ice2.html"
          - text: "ice3"
            href: "ICE/ex3/ice3.html"
          - text: "ice4"
            href: "ICE/ex4/ice4.html"
          - text: "ice5"
            href: "ICE/ex5/ice5.html"
          - text: "ice6"
            href: "ICE/ex6/ice6.html"
      - text: "Takehomes"
        menu:
          - text: "th1"
            href: "THE/THE1/takehome1.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

