project:
  type: website

website:
  title: "415"
  navbar:
    left:
      - text: "HOEs"
        menu: 
          - text: "ex1"
            href: "HOE/ex1/ex1.html"
          - text: "ex2"
            href: "HOE/ex2/ex2.html"
          - text: "ex3"
            href: "HOE/ex3/ex3.html"
          - text: "ex4"
            href: "HOE/ex4/ex4.html"
          - text: "ex5"
            href: "HOE/ex5/ex5.html"
          - text: "ex6"
            href: "HOE/ex6/ex6.html"
          - text: "ex7"
            href: "HOE/ex7/ex7.html"
      - text: "ICEs"
        menu:
          - text: "ice1"
            href: "ICE/ex1/ice1.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

