project:
  type: website

website:
  title: "415"
  navbar:
    left:
      - text: "exercises"
        menu: 
          - text: "ex1"
            href: "HOE/ex1/ex1.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

