---
title: "ICE5"
date: "September 16, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  freeze: true
---
# Geographically Weighted Statistics

## Install/Launch R Packages
```{r}

pacman::p_load(sf, spdep, tmap, tidyverse, knitr, GWmodel)
```


```{r}
#| eval: false
hunan_sf  <- st_read(dsn = "data/geospatial", layer =  "Hunan")
```

```{r}
#| eval: false
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

Join the dataframes together:

```{r}
#| eval: false
hunan_sf <- left_join(hunan_sf,hunan2012)%>%
  select(1:3, 7, 15, 16, 31, 32)
```

save file 
```{r}
#| eval: false
write_rds(hunan_sf, "data/rds/hunan_sf.rds")
```

```{r}
hunan_sf <- read_rds("data/rds/hunan_sf.rds")
```

```{r}
hunan_sp <- as_Spatial(hunan_sf)
```

```{r}
bw_AIC <- bw.gwr(GDPPC ~ 1, data = hunan_sp, approach = "AIC", adaptive = TRUE, kernel = "bisquare", longlat = T)
```

```{r}
bw_AIC
```

```{r}
bw_CV <- bw.gwr(GDPPC ~ 1, data = hunan_sp, approach = "CV", adaptive = TRUE, kernel = "bisquare", longlat = T)
```


```{r}
bw_CV
```
fixed bandwidth
```{r}
#| eval: false
bw_AIC <- bw.gwr(GDPPC ~ 1, data = hunan_sp, approach = "AIC", adaptive = FALSE, kernel = "bisquare", longlat = T)
```

```{r}
#| eval: false
bw_CV <- bw.gwr(GDPPC ~ 1, data = hunan_sp, approach = "CV", adaptive = FALSE, kernel = "bisquare", longlat = T)
```

geoweighted summary stats
```{r}
gwstat <- gwss(data = hunan_sp, vars = "GDPPC", bw = bw_AIC, kernel = "bisquare", adaptive = TRUE, longlat = T)
```

```{r}
gwstat_df <- as.data.frame(gwstat$SDF)
```

```{r}
hunan_gstat <- cbind(hunan_sf,gwstat_df)
```

viz
```{r}
tm_shape(hunan_gstat) + tm_fill("GDPPC_LM",
                                n = 5,
                                style = "quantile") +
  tm_borders(alpha = 0.5) +
  tm_layout(main.title = "Dist of geoweighted mean",
            main.title.position = "center",
            main.title.size = 1.0,
            legend.text.size =0.8,
            legend.height = 1.0 ,
            legend.width = 1.0,
            frame = TRUE)
```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```


