---
title: "ICE 2"
date: "August 26, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  freeze: true
---

```{r}
pacman::p_load(sf, tidyverse, tmap)

```

```{r}
#| output: false
mpsz14_shp <- st_read(dsn = "data/", layer = "MP14_SUBZONE_WEB_PL")
```

```{r}
#| output: false
mpsz14_kml <- st_write(mpsz14_shp, "data/MP14_SUBZONE_WEB_PL.kml", delete_dsn = TRUE)
```

```{r}

mpsz19_shp <- st_read(dsn = "data/", layer = "MPSZ-2019")
```

```{r}

mpsz19_kml <- st_read("data/MasterPlan2019SubzoneBoundaryNoSeaKML.kml")

```

```{r}
mpsz19_shp <- st_read(dsn = "data/", layer = "MPSZ-2019") %>% st_transform(crs = 3414)
```

```{r}
preschool <- st_read("data/PreSchoolsLocation.kml") %>% st_transform(crs = 3414)
```

check the coordinate system
```{r}
st_crs(mpsz19_shp)
```

```{r}
popdata <- read.csv("data/respopagesextod2023.csv")
```

```{r}
popdata2023 <- popdata %>% 
  group_by(PA, SZ, AG) %>%
  summarise(`POP` = sum(`Pop`)) %>% 
  ungroup() %>%
  pivot_wider(names_from = AG, values_from = POP)

colnames(popdata2023)
```

```{r}
popdata2023 <- popdata2023 %>%
  mutate_at(.vars = vars(PA, SZ),
            .funs = list(toupper))
```



```{r}
pop2023_mpsz <- left_join(popdata2023, mpsz19_shp, by = c("SZ" = "SUBZONE_N"))
```



```{r}
mpsz_pop2023 <- left_join(mpsz19_shp, popdata2023, by = c("SUBZONE_N" = "SZ"))
```




